version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  web:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  db-data:
