# Generated by Django 5.1.7 on 2025-05-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('components', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('metric_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('dimension', models.IntegerField(default=4)),
                ('coordinates', models.JSONField(blank=True, default=list, null=True)),
                ('metric_data', models.JSONField(blank=True, default=list, null=True)),
                ('christoffel_symbols', models.JSONField(blank=True, default=list, null=True)),
                ('riemann_tensor', models.JSONField(blank=True, default=list, null=True)),
                ('ricci_tensor', models.JSONField(blank=True, default=list, null=True)),
                ('scalar_curvature', models.CharField(blank=True, max_length=255, null=True)),
                ('einstein_tensor', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
